### ISSUE TITLE
Use string.casefold() before sorting files

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-submission-ui#83]
![Screenshot 2019-06-04 16 17 10](https://user-images.githubusercontent.com/746253/58911017-ee49f300-86e4-11e9-8268-2a58ef3bec82.png)

> Nit: python's lexicographic sorting feels unnatural for a list of files/folders since it's not how most operating systems (AFAIK) sort files/folder names. I would be inclined to apply `string.casefold()` before sorting.

_Originally posted by @mhl10 in https://github.com/arXiv/arxiv-submission-ui/pull/80_

**Comment by jimentwood** [comment]
It also looks like the sort lists directories embedded in the same sort as files in the top level sort.

So rather than 
/e_file1.tex
/g_file2.sty
/figures/picture.png

it currently looks like
/e_file1.tex
/figures/picture.png
/g_file2.sty
which may be tricky to read

![Screenshot from 2019-06-07 13-15-28](https://user-images.githubusercontent.com/11538356/59121721-ebd6db80-8926-11e9-901a-3a04c1c79dc6.png)

**Comment by bdc34** [comment]
I cannot get to this stage with the current develop branch.

**Comment by bdc34** [comment]
I'm going to try this without a file upload.

**Comment by bdc34** [comment]
![ordered_upload_files](https://user-images.githubusercontent.com/1616/59466775-209dd380-8dfc-11e9-9037-d0ebc4965e0c.png)
